name: epic-models
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - ipykernel=5.3.4
  - ipython=7.18.1
  - numpy=1.19.1
  - pandas=1.1.1
  - pillow=7.2.0
  - pip=20.2.2
  - python=3.8.5
  - pytorch=1.6.0
  - pytorch-lightning=0.9.0
  - pyyaml=5.3.1
  - scipy=1.5.2
  - setuptools=49.6.0
  - tensorboard=2.2.0
  - torchvision=0.7.0
  - tqdm=4.48.2
  - yaml=0.2.5
  - pip:
    - hydra-core==1.0.0
    - hydra_colorlog==1.0.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.0.1
    - ipdb==0.13.3
    - gulpio==540.66
    - hydra_colorlog==1.0.0
    - moviepy==1.0.3
